[package]
name = "all-rust-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.8.1"
axum-server = "0.7.1"
hyper = "1.6.0"

[dev-dependencies]
anyhow = "1"
